language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.9
os:
  - linux
script:
  - dotnet restore
  - dotnet build ./src/Evolve/Evolve.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core.Test/Evolve.Core.Test.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core.Test.Driver/Evolve.Core.Test.Driver.csproj -c Release -f netcoreapp2.0
  - dotnet build ./test/Evolve.Core.Test.Resources.SupportedDrivers/Evolve.Core.Test.Resources.SupportedDrivers.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core2.Test.Resources.SupportedDrivers/Evolve.Core2.Test.Resources.SupportedDrivers.csproj -c Release -f netcoreapp2.0
  - dotnet test ./test/Evolve.Core.Test/Evolve.Core.Test.csproj -c Release -f netcoreapp1.0
  - dotnet test ./test/Evolve.Core.Test.Driver/Evolve.Core.Test.Driver.csproj -c Release -f netcoreapp2.0
