language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNETPATH: /home/travis/.dotnet
sudo: required
mono: 5.8.0
dotnet: none #2.1.300
os: linux
install:
  - sudo apt install libunwind8
  - wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
  - chmod +x /tmp/dotnet-install.sh
  - /tmp/dotnet-install.sh -v 2.1.300
  - /tmp/dotnet-install.sh -v 2.0.7 --shared-runtime
  - /tmp/dotnet-install.sh -v 1.1.8 --shared-runtime
  - /tmp/dotnet-install.sh -v 1.0.11 --shared-runtime
  - export PATH=$DOTNETPATH:$PATH
  - dotnet --info
