#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}
skip_non_tags: false
image: Visual Studio 2017
configuration: Release

# enable service required for build/tests
services:
- postgresql
- mssql2016
- mysql

# scripts that are called at very beginning, before repo cloning
init:
- cmd: SET PGUSER=postgres
- cmd: SET PGPASSWORD=Password12!
- cmd: SET MYSQL_PWD=Password12!
- cmd: SET PATH=C:\Program Files\PostgreSQL\9.5\bin\;%PATH%
- cmd: SET PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin\;%PATH%
- cmd: SET PATH=C:\projects\evolve\packages\xunit.runner.console.2.3.0\tools\net452\;%PATH%

#---------------------------------#
#              build              #
#---------------------------------#

# scripts to run before build
before_build:
- ps: dotnet restore
- ps: nuget restore

# build
build:
  verbosity: minimal

#---------------------------------#
#              tests              #
#---------------------------------#

# scripts to run before tests
before_test:
- cmd: createdb my_database
- cmd: mysql -e "create database my_database;" --user=root

# tests
test_script:
- ps: cd test/Evolve.Core.Test/
- ps: dotnet test
- ps: cd ../..

- ps: cd test/Evolve.Core.Test.Driver/
- ps: dotnet test
- ps: cd ../..

- cmd: xunit.console.exe test\Evolve.Test\bin\%CONFIGURATION%\Evolve.Test.dll
- cmd: xunit.console.exe test\Evolve.IntegrationTest.MySQL\bin\%CONFIGURATION%\Evolve.IntegrationTest.MySQL.dll
- cmd: xunit.console.exe test\Evolve.IntegrationTest.PostgreSQL\bin\%CONFIGURATION%\Evolve.IntegrationTest.PostgreSQL.dll
- cmd: xunit.console.exe test\Evolve.IntegrationTest.SQLServer\bin\%CONFIGURATION%\Evolve.IntegrationTest.SQLServer.dll
- cmd: xunit.console.exe test\Evolve.IntegrationTest.SQLite\bin\%CONFIGURATION%\Evolve.IntegrationTest.SQLite.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# scripts to run after tests
after_test:
- ps: cd src/Evolve
- ps: nuget pack Evolve.nuspec
- ps: cd ../..

artifacts:
- path: '**\Evolve*.nupkg'
